# How to run this?  docker-compose up --abort-on-container-exit --build
version: '2'
services:
  firefox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6901:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6900:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  tests:
    image: maven_tests:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - hub
    volumes:
      - ./.m2:/root/.m2
    command: ["./wait-for-grid.sh", "mvn", "clean", "test"]
