name: GitHub Actions CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up --abort-on-container-exit --build
